# Generated by Django 5.2.8 on 2026-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prescription',
            new_name='prescriptio_organiz_6299ac_idx',
            old_name='presc_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='prescription',
            new_name='prescriptio_organiz_a96b62_idx',
            old_name='presc_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='prescription',
            new_name='prescriptio_custome_cb0032_idx',
            old_name='presc_phone_idx',
        ),
    ]
