# Generated by Django 5.2.12 on 2026-05-21 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_rename_network_mem_org_status_idx_authapp_pha_organiz_b86818_idx_and_more'),
        ('prescriptions', '0002_rename_presc_org_status_idx_prescriptio_organiz_6299ac_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('clinic', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_network_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribers', to='authapp.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.prescriber'),
        ),
        migrations.AddIndex(
            model_name='prescriber',
            index=models.Index(fields=['organization', 'name'], name='prescriptio_organiz_65404a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriber',
            index=models.Index(fields=['license_number'], name='prescriptio_license_04fc44_idx'),
        ),
    ]
