# Generated by Django 5.2.8 on 2026-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_rename_network_mem_org_status_idx_authapp_pha_organiz_b86818_idx_and_more'),
        ('prescriptions', '0006_prescriber_password'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescriber',
            name='prescriptio_organiz_65404a_idx',
        ),
        migrations.AddIndex(
            model_name='prescriber',
            index=models.Index(fields=['name'], name='prescriptio_name_c9c9d9_idx'),
        ),
    ]
