# Generated by Django 5.2.12 on 2026-05-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_rename_network_mem_org_status_idx_authapp_pha_organiz_b86818_idx_and_more'),
        ('prescriptions', '0007_remove_prescriber_prescriptio_organiz_65404a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='authapp.organization'),
        ),
    ]
