# Generated by Django 5.2.12 on 2026-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescription_org_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='source',
            field=models.CharField(blank=True, default='pharmacy', max_length=30),
        ),
    ]
