# Generated by Django 5.2.12 on 2026-05-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_add_prescription_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriber',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage (0–100) earned on dispensed prescription sales', max_digits=5),
        ),
        migrations.CreateModel(
            name='PrescriberCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Unknown', max_length=200)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prescriptions.prescriber')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescriber', 'status'], name='prescriptio_prescri_3d632f_idx'), models.Index(fields=['prescription'], name='prescriptio_prescri_bba23f_idx')],
            },
        ),
    ]
