# Generated by Django 5.2.12 on 2026-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_prescriber_commission_rate_and_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriber',
            name='consult_fee_a',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='consult_fee_b',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='consult_fee_c',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='consult_fee_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='consult_fee_e',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation_category',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
