# Generated by Django 5.2.12 on 2026-06-17 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prescriber_consult_fee_a_prescriber_consult_fee_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Unknown', max_length=200)),
                ('consultation_category', models.CharField(blank=True, default='', max_length=1)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payouts', to='prescriptions.prescriber')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payout', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prescriber', 'status'], name='prescriptio_prescri_dcd374_idx')],
            },
        ),
    ]
