# Generated by Django 5.2.12 on 2026-09-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_consultationpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='last_refill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='next_refill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_allowed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='refills_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
