# Generated by Django 5.2.8 on 2026-03-24 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organization_pharmuser_organization'),
        ('pos', '0002_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='sale',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_checks', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='authapp.organization'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='authapp.organization'),
        ),
    ]
