# Generated by Django 5.2.12 on 2026-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_expense_organization_paymentrequest_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheck',
            name='store_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='Which store this stock check belongs to', max_length=20),
        ),
    ]
