# Generated by Django 5.2.12 on 2026-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_store_type_to_stock_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='return_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='approved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
