# Generated by Django 5.2.12 on 2026-04-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_decimal_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcheckitem',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockcheckitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
