# Generated by Django 5.2.12 on 2026-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_sale_shift_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
