# Generated by Django 5.2.12 on 2026-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_fix_legacy_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('partial_return', 'Partial Return'), ('credit', 'Credit')], default='completed', max_length=20),
        ),
    ]
