# Generated by Django 5.1.5 on 2025-02-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_procurementitem_exp_date_procurementitem_markup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementitem',
            old_name='exp_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='wholesaleprocurementitem',
            old_name='exp_date',
            new_name='expiry_date',
        ),
    ]
