# Generated by Django 5.1.7 on 2025-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_exp_date_procurementitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleprocurement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
