# Generated by Django 5.1.5 on 2025-07-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_edited_at_chatmessage_file_attachment_and_more'),
        ('chat', '0002_enhanced_chat_features'),
    ]

    operations = [
    ]
