# Generated by Django 4.2.29 on 2026-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organization_pharmuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_environment', models.CharField(choices=[('dev', 'Development'), ('prod', 'Production')], default='dev', help_text='Desired environment. Takes effect after server restart.', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Block all API traffic with a 503 response.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
