# Generated by Django 5.2.12 on 2026-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
