# Generated by Django 5.2.8 on 2026-04-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='authapp_act_organiz_bc4850_idx',
            old_name='authapp_act_org_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='authapp_act_organiz_ec005b_idx',
            old_name='authapp_act_org_cat_idx',
        ),
    ]
