# Generated by Django 5.2.8 on 2026-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_authapp_act_org_ts_idx_authapp_act_organiz_bc4850_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='permission',
            field=models.CharField(choices=[('viewReports', 'viewReports'), ('manageUsers', 'manageUsers'), ('manageSettings', 'manageSettings'), ('viewNotifications', 'viewNotifications'), ('viewSubscription', 'viewSubscription'), ('retailPOS', 'retailPOS'), ('wholesalePOS', 'wholesalePOS'), ('viewWholesale', 'viewWholesale'), ('readInventory', 'readInventory'), ('writeInventory', 'writeInventory'), ('readCustomers', 'readCustomers'), ('writeCustomers', 'writeCustomers'), ('manageExpenses', 'manageExpenses'), ('manageSuppliers', 'manageSuppliers'), ('processPayments', 'processPayments'), ('manageTransfers', 'manageTransfers'), ('readPrescriptions', 'readPrescriptions'), ('writePrescriptions', 'writePrescriptions')], max_length=50),
        ),
    ]
