# Generated by Django 5.2.12 on 2026-05-18 22:22
# Fixed: server had old 0011 without AddIndex; use SeparateDatabaseAndState so
# DB side uses idempotent DROP/CREATE (SQLite-compatible) while state side
# still performs RenameIndex (works because Django reads the current 0011 file).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_commissionconfig'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop old-named indexes if they exist (no-op if server never had them)
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "network_mem_org_status_idx";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS "authapp_pha_organiz_b86818_idx"'
                        ' ON "authapp_pharmacynetworkmembership" ("organization_id", "status");'
                    ),
                    reverse_sql='DROP INDEX IF EXISTS "authapp_pha_organiz_b86818_idx";',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "network_mem_net_status_idx";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS "authapp_pha_network_6a24fa_idx"'
                        ' ON "authapp_pharmacynetworkmembership" ("network_id", "status");'
                    ),
                    reverse_sql='DROP INDEX IF EXISTS "authapp_pha_network_6a24fa_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='pharmacynetworkmembership',
                    new_name='authapp_pha_organiz_b86818_idx',
                    old_name='network_mem_org_status_idx',
                ),
                migrations.RenameIndex(
                    model_name='pharmacynetworkmembership',
                    new_name='authapp_pha_network_6a24fa_idx',
                    old_name='network_mem_net_status_idx',
                ),
            ],
        ),
    ]
