# Generated by Django 5.2.12 on 2026-05-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_commissionconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pharmacynetworkmembership',
            new_name='authapp_pha_organiz_b86818_idx',
            old_name='network_mem_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacynetworkmembership',
            new_name='authapp_pha_network_6a24fa_idx',
            old_name='network_mem_net_status_idx',
        ),
    ]
