# Generated by Django 5.2.12 on 2026-08-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_organization_last_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('token_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'unique_together': {('key', 'token_hash')},
            },
        ),
    ]
