# Generated by Django 5.2.12 on 2026-08-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_organization_last_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='application/json', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='authapp_ide_created_34638e_idx')],
            },
        ),
    ]
