# Generated by Django 5.2.12 on 2026-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_organization_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_network_patient',
            field=models.BooleanField(default=False, help_text='Visible to all pharmacies in the same network for prescription lookup.'),
        ),
    ]
