# Generated by Django 5.2.8 on 2026-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('dosage_form', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
