# Generated by Django 4.2.29 on 2026-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='Which dispensing store this item belongs to', max_length=20),
        ),
    ]
