# Generated by Django 4.2.29 on 2026-03-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_store_field_to_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailItem',
            fields=[
            ],
            options={
                'verbose_name': 'Retail Item',
                'verbose_name_plural': 'Retail Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='WholesaleItem',
            fields=[
            ],
            options={
                'verbose_name': 'Wholesale Item',
                'verbose_name_plural': 'Wholesale Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.item',),
        ),
    ]
