# Generated by Django 5.2.8 on 2026-03-24 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organization_pharmuser_organization'),
        ('inventory', '0003_retailitem_wholesaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authapp.organization'),
        ),
    ]
