# Generated by Django 5.2.12 on 2026-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
