# Generated by Django 5.2.12 on 2026-04-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_max_branches',
            field=models.IntegerField(blank=True, help_text='Override max branches. -1 = unlimited. Leave blank for plan default.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_max_items',
            field=models.IntegerField(blank=True, help_text='Override max inventory items. -1 = unlimited. Leave blank for plan default.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_max_transactions',
            field=models.IntegerField(blank=True, help_text='Override max transactions/month. -1 = unlimited. Leave blank for plan default.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom_max_users',
            field=models.IntegerField(blank=True, help_text='Override max staff users. -1 = unlimited. Leave blank for plan default.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='extra_features',
            field=models.JSONField(blank=True, default=list, help_text='Feature keys enabled for this org beyond the plan default. Valid keys: pos, inventory, customers, user_management, basic_reports, advanced_reports, wholesale, export_data, multi_branch, api_access, priority_support, white_label'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='removed_features',
            field=models.JSONField(blank=True, default=list, help_text='Feature keys explicitly disabled for this org (overrides plan default).'),
        ),
    ]
