# Generated by Django 5.2.12 on 2026-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_add_feature_overrides_and_custom_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, max_length=20)),
                ('feature_key', models.CharField(choices=[('pos', 'Point of Sale'), ('inventory', 'Inventory Management'), ('customers', 'Customer Management'), ('user_management', 'User Management'), ('basic_reports', 'Basic Reports'), ('advanced_reports', 'Advanced Reports'), ('wholesale', 'Wholesale Module'), ('export_data', 'Export Data'), ('multi_branch', 'Multi-Branch'), ('api_access', 'API Access'), ('priority_support', 'Priority Support'), ('white_label', 'White Label')], help_text='Internal key used by the Flutter app to gate feature access.', max_length=50)),
                ('feature_label', models.CharField(help_text='Display name shown in the subscription screen feature table.', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to remove this feature from the plan.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Controls the row order in the feature comparison table.')),
            ],
            options={
                'verbose_name': 'Plan Feature Flag',
                'verbose_name_plural': 'Plan Feature Flags',
                'ordering': ['sort_order', 'plan', 'feature_key'],
                'unique_together': {('plan', 'feature_key')},
            },
        ),
    ]
