# Generated by Django 5.2.12 on 2026-04-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_remove_api_access_white_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('expiring', 'Trial Expiring'), ('expired', 'Expired'), ('active', 'Active'), ('pending', 'Pending Approval'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
