# Generated by Django 5.2.12 on 2026-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
