# Generated by Django 5.1.5 on 2025-02-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_wholesalestockcheckitem_stock_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkstockadjustmentitem',
            name='bulk_adjustment',
        ),
        migrations.RemoveField(
            model_name='bulkstockadjustmentitem',
            name='stock_check_item',
        ),
        migrations.DeleteModel(
            name='BulkStockAdjustment',
        ),
        migrations.DeleteModel(
            name='BulkStockAdjustmentItem',
        ),
    ]
