# Generated by Django 5.1.5 on 2025-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_stockcheckitem_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheckitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
