# Generated by Django 5.1.5 on 2025-02-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_stockcheckitem_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalestockcheckitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_item', to='store.item'),
        ),
    ]
