# Generated by Django 5.1.5 on 2025-02-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_wholesalestockcheckitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalestockcheckitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_item', to='store.wholesaleitem'),
        ),
    ]
