# Generated by Django 5.1.5 on 2025-02-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_transferrequest_transferlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='destination_content_type',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='source_content_type',
        ),
        migrations.DeleteModel(
            name='TransferLog',
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
    ]
