# Generated by Django 5.1.5 on 2025-02-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='from_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
