# Generated by Django 5.1.5 on 2025-02-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_transferrequest_from_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
