# Generated by Django 5.1.5 on 2025-02-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
