# Generated by Django 5.1.5 on 2025-02-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_storeitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='supplier',
        ),
    ]
