# Generated by Django 5.1.5 on 2025-02-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_expensecategory_monthlyreport_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
    ]
