# Generated by Django 5.1.7 on 2025-03-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_receipt_options_receipt_has_returns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='store.sales'),
        ),
    ]
