# Generated by Django 5.1.7 on 2025-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Wholesale Settings',
                'verbose_name_plural': 'Wholesale Settings',
            },
        ),
    ]
