# Generated by Django 5.1.7 on 2025-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_wholesaleitem_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wholesalecart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
