# Generated by Django 5.1.7 on 2025-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_cart_quantity_alter_wholesalecart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
