# Generated by Django 5.1.7 on 2025-04-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_dispensinglog_quantity'),
        ('store', '0042_alter_dispensinglog_quantity'),
    ]

    operations = [
    ]
