# Generated by Django 5.1.7 on 2025-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_cart_unit_alter_dispensinglog_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
