# Generated by Django 5.1.7 on 2025-04-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_formulation_dosage_form_alter_item_dosage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='dosage_form',
            field=models.CharField(default='dosage_form', max_length=255),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
