# Generated by Django 5.1.5 on 2025-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_receipt_status_alter_wholesalereceipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='wallet_went_negative',
            field=models.BooleanField(default=False, help_text="Indicates if customer's wallet went negative during this transaction"),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='wallet_went_negative',
            field=models.BooleanField(default=False, help_text="Indicates if customer's wallet went negative during this transaction"),
        ),
    ]
