# Generated by Django 5.1.5 on 2025-08-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_add_wholesale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied to this dispensed item', max_digits=10),
        ),
    ]
