# Generated by Django 5.1.5 on 2025-08-08 07:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_add_discount_to_dispensing_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Partially Returned', 'Partially Returned'), ('Dispensed', 'Dispensed')], db_index=True, default='Dispensed', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='dosage_form',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaleitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['-created_at'], name='store_dispe_created_5c1867_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['name', 'status'], name='store_dispe_name_51bd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['user', '-created_at'], name='store_dispe_user_id_7a2bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['status', '-created_at'], name='store_dispe_status_4ee3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'brand'], name='store_item_name_88c47a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'dosage_form'], name='store_item_name_240fde_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['name', 'brand'], name='store_whole_name_5feb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesaleitem',
            index=models.Index(fields=['name', 'dosage_form'], name='store_whole_name_d44a40_idx'),
        ),
    ]
