# Generated by Django 5.1.5 on 2025-08-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_add_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcheckitem',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockcheckitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wholesalestockcheckitem',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wholesalestockcheckitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
