# Generated by Django 5.1.5 on 2025-08-20 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_update_stock_check_decimal_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_returned',
            field=models.BooleanField(default=False, help_text='Indicates if this receipt has been returned'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount returned', max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when the receipt was returned', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='return_processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_receipt_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sales',
            name='is_returned',
            field=models.BooleanField(default=False, help_text='Indicates if this sale has been returned'),
        ),
        migrations.AddField(
            model_name='sales',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount returned', max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when the sale was returned', null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='return_processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='is_returned',
            field=models.BooleanField(default=False, help_text='Indicates if this wholesale receipt has been returned'),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount returned', max_digits=10),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when the wholesale receipt was returned', null=True),
        ),
        migrations.AddField(
            model_name='wholesalereceipt',
            name='return_processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_wholesale_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
