# Generated by Django 5.1.7 on 2025-04-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Pharmacist', 'Pharmacist'), ('Pharm-Tech', 'Pharm-Tech'), ('Salesperson', 'Salesperson')], max_length=200, null=True),
        ),
    ]
