# Generated by Django 5.1.5 on 2025-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Pharmacist', 'Pharmacist'), ('Pharm-Tech', 'Pharm-Tech'), ('Salesperson', 'Salesperson'), ('Wholesale Manager', 'Wholesale Manager'), ('Wholesale Operator', 'Wholesale Operator'), ('Wholesale Salesperson', 'Wholesale Salesperson')], max_length=200, null=True),
        ),
    ]
